### ISSUE TITLE
Persistent data

### ISSUE THREAD

**Issue by SegiH** [BenEvenTsur/xubuntu-novnc#2]
I pulled the image for xubuntu-novnc and I love it. There doesn't seem to be any documentation any where and I was wondering if it possible to set up persistent volume storage. The Docker hub page does not mention this and I would like to be able to retain data after restarting my container.

Is there a path that I can set to have persistent storage

**Comment by ProtocolNebula** [comment]
Hi,
Maybe is too late, but there's an extract of my `docker-compose.yml` that I use for an instance with VSCODE

```yml
version: '3'
services:
  vscode:
    container_name: vscode
    # in fact I'm using an edit of beneventsur/visual-studio-code
    image: "beneventsur/xubuntu"
    volumes:
      # Your volumes, the 1rst is readonly
      - /volume1/:/shared/:ro
      # This will store the whole /root (home) folder to my computer
      - /volume1/homes/protocolnebula/dockers-data/home:/root/
    restart: unless-stopped
    privileged: true
    networks:
      - vscode
    ports:
      - 5901:5901
      - 6080:6080
    environment:
      - PASSWORD=YOURPASSWORDHERE
      - WIDTH=1440
      - HEIGHT=900
```
